# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml
#

trigger:
- main

pool:
  name: Default

steps:
- task: Checkmarx AST@3
  displayName: 'Checkmarx AST'
  inputs:
    CheckmarxService: 'AST'
    projectName: '$(Build.Repository.Name)'
    branchName: '$(Build.SourceBranchName)'
    tenantName: 'cx_ps_apac_test_james_bostock'
    additionalParams: '--report-format sarif --scs-repo-url $(Build.Repository.Uri) --scs-repo-token $(System.AccessToken)'
- task: PublishBuildArtifacts@1
  displayName: 'Publish artifact: CodeAnalysisLogs'
  inputs:
    PathToPublish: 'cx_result.sarif'
    ArtifactName: CodeAnalysisLogs
